### ISSUE TITLE
Suche optisch anpassen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-servicekatalog#12]
<img width="1158" alt="grafik" src="https://github.com/RRZE-Webteam/rrze-servicekatalog/assets/1070669/4103e74c-094b-4d7d-85b3-aaa4b858f383">

Bitte den Button hinter dem Suchstringeingabe in der ersten Zeile.

Die Optionen wie bisher auf der zweiten Zeile.
Ebenso wie bei meinstudium:
<img width="1477" alt="grafik" src="https://github.com/RRZE-Webteam/rrze-servicekatalog/assets/1070669/7b52e872-ff13-41df-94b7-0853e3cf86aa">

**Comment by cassandre** [comment]
Die Filteroptionen unterhalb des Suche-Buttons anzuzeigen ist extrem verwirrend. Die Benutzer gehen dann nicht davon aus, dass sie oben noch mal auf Suchen klicken müssen, nachdem sie unten was ausgewählt haben.

**Comment by xwolfde** [comment]
Das wurde ja auch nicht gefordert. Hier geht es um die Optik.
Die lineare Reihenfolge des Klicks oder der Tabs kann von der optischen Darstellung abweichen.
Ausserdem kannst du die Zusatzoptionen auch auslösen, wenn sie geändert werden, ohne dass hierfür auf den Button geklickt wurde. DIeser Punkt wird übrigens bei meinstudium für Desktop-User auch noch angepasst.

**Comment by cassandre** [comment]
erledigt in v1.1.0
